<a href="https://colab.research.google.com/github/mahesh-ml/MLBasics/blob/main/word_embeddings.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [4]:
word_to_index = {'I':0, 'love':1 , 'eating':2 , 'and':3 , 'sleeping':4}
embeddings = nn.Embedding(5,7)
word_index = torch.tensor([word_to_index['love']])
print(word_index)

tensor([1])


In [5]:
love = embeddings(word_index)
print(love)
print(love.shape)

tensor([[-0.7758, -0.4335,  0.4740, -0.1518, -0.9459, -0.1036, -0.5740]],
       grad_fn=<EmbeddingBackward0>)
torch.Size([1, 7])


In [9]:
all_ind = torch.tensor([w for w in range(5)], dtype=torch.long)
all_Words = embeddings(all_ind)
print(all_ind)
print(all_Words)

tensor([0, 1, 2, 3, 4])
tensor([[-4.3883e-01, -5.1261e-01,  1.2758e-01,  5.5139e-01,  2.3336e+00,
         -5.3295e-02,  5.4954e-01],
        [-7.7580e-01, -4.3355e-01,  4.7404e-01, -1.5181e-01, -9.4594e-01,
         -1.0360e-01, -5.7397e-01],
        [-6.8668e-01,  6.5765e-01,  3.5345e-01,  1.6207e+00,  1.9170e+00,
          1.6829e+00, -1.0924e+00],
        [ 6.5266e-01,  1.4497e-01,  9.2186e-01,  1.1011e+00, -3.3312e-01,
         -1.2189e+00,  1.3038e-01],
        [-2.7297e-02,  1.5296e-03, -9.4952e-01,  6.8616e-01, -2.2814e-01,
          5.7127e-02, -1.4375e+00]], grad_fn=<EmbeddingBackward0>)
